from django.db import models

# Create your models here.


class PersonajeDatosBasicosModel(models.Model):
    id = models.AutoField(primary_key=True)
    nombrepj=models.CharField(max_length=20)
    jugador=models.CharField(max_length=20)
    genero=models.CharField(max_length=20)
    estatura=models.DecimalField(max_digits=3, decimal_places=2)
    peso=models.IntegerField()
    raza=models.CharField(max_length=20)
    edad=models.IntegerField()
    pelo=models.CharField(max_length=15)
    ojos=models.CharField(max_length=15)
    especialfisico=models.CharField(max_length=50)
    personalidad=models.CharField(max_length=20, null=True, blank=True)
    motivacion=models.CharField(max_length=20, null=True, blank=True)
    alineamiento=models.CharField(max_length=20, null=True, blank=True)
    status=models.CharField(max_length=20, null=True, blank=True)
    profesion=models.CharField(max_length=10)
    nivel=models.IntegerField(default=0)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    dominiomagico=models.CharField(max_length=20)

class PersonajeCaracteristicasModel(models.Model):
#   id_datosbasicos=models.OneToOneField("PersonajeDatosBasicosModel", on_delete=models.CASCADE)
    fue=models.IntegerField()
    agi=models.IntegerField()
    con=models.IntegerField()
    int=models.IntegerField()
    i=models.IntegerField()
    pre=models.IntegerField()
    apa=models.IntegerField()

class PersonajeGradosModel(models.Model):
    sin_armadura=models.IntegerField()
    cuero=models.IntegerField()
    cuero_endurecido=models.IntegerField()
    cota_de_mallas=models.IntegerField()
    coraza=models.IntegerField()
    de_filo=models.IntegerField()
    contundente=models.IntegerField()
    a_2_manos=models.IntegerField()
    arrojadizas=models.IntegerField()
    proyectiles=models.IntegerField()
    armas_de_asta=models.IntegerField()
    escudo=models.IntegerField()
    trepar=models.IntegerField()
    montar=models.IntegerField()
    nadar=models.IntegerField()
    rastrear=models.IntegerField()
    emboscar=models.IntegerField()
    acechar_y_esconderse=models.IntegerField()
    abrir_cerraduras=models.IntegerField()
    desactivar_trampas=models.IntegerField()
    percepcion=models.IntegerField()
    liderazgo_e_influencia=models.IntegerField()
