# Generated by Django 4.0.5 on 2023-03-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razastabla1',
            old_name='a_2_manos',
            new_name='a_dos_manos',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='agi',
            new_name='agilidad',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='con',
            new_name='constitucion',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='fue',
            new_name='fuerza',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='i',
            new_name='inteligencia',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='int',
            new_name='intuicion',
        ),
        migrations.RenameField(
            model_name='razastabla1',
            old_name='pre',
            new_name='presencia',
        ),
        migrations.RenameField(
            model_name='razastabla2',
            old_name='a_2_manos',
            new_name='a_dos_manos',
        ),
    ]
