# Generated by Django 4.0.5 on 2023-04-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0002_rename_a_2_manos_razastabla1_a_dos_manos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pj', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estatura', models.FloatField()),
                ('peso', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('pelo', models.CharField(max_length=255)),
                ('ojos', models.CharField(max_length=255)),
                ('especial_fisico', models.CharField(max_length=255)),
                ('personalidad', models.CharField(max_length=255)),
                ('motivacion', models.CharField(max_length=255)),
                ('alineamiento', models.CharField(choices=[('Legal Bueno', 'Legal Bueno'), ('Legal Neutral', 'Legal Neutral'), ('Legal Malo', 'Legal Malo'), ('Neutral Bueno', 'Neutral Bueno'), ('Neutral Neutral', 'Neutral Neutral'), ('Neutral Malo', 'Neutral Malo'), ('Caótico Bueno', 'Caótico Bueno'), ('Caótico Neutral', 'Caótico Neutral'), ('Caótico Malo', 'Caótico Malo')], max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RazaYProfesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(choices=[('Enano', 'Enano'), ('Umli', 'Umli'), ('Elfos Noldor', 'Elfos Noldor'), ('Elfos Sindar', 'Elfos Sindar')], max_length=100)),
                ('profesion', models.CharField(choices=[('guerrero', 'Guerrero'), ('montaraz', 'Montaraz'), ('explorador', 'Explorador'), ('mago', 'Mago'), ('animista', 'Animista'), ('bardo', 'Bardo')], max_length=100)),
                ('dominio_magico', models.CharField(choices=[('esencia', 'Esencia'), ('canalizacion', 'Canalización')], max_length=100)),
            ],
        ),
    ]
