# Generated by Django 4.1.7 on 2023-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0003_datosbasicos_razayprofesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razayprofesion',
            name='raza',
            field=models.CharField(choices=[('Enano', 'Enano'), ('Umli', 'Umli'), ('Elfos Noldor', 'Elfos Noldor'), ('Elfos Sindar', 'Elfos Sindar'), ('Elfos Silvano', 'Elfos Silvano'), ('Medio Elfos', 'Medio Elfos'), ('Hobbit', 'Hobbit'), ('Beórnidas', 'Beórnidas'), ('Núm. Negros', 'Núm. Negros'), ('Corsarios', 'Corsarios'), ('Dorwinrim', 'Dorwinrim'), ('Dúnedain', 'Dúnedain'), ('Dunledinos', 'Dunledinos'), ('Hombres del Este', 'Hombres del Este'), ('Haradrim del Norte', 'Haradrim del Norte'), ('Haradrim del Sur', 'Haradrim del Sur'), ('Lossoth', 'Lossoth'), ('Rohirrim', 'Rohirrim'), ('Campesinos', 'Campesinos'), ('Burgueses', 'Burgueses'), ('Variags', 'Variags'), ('H. de los Bosques', 'H. de los Bosques'), ('Woses', 'Woses'), ('Orcos', 'Orcos'), ('Uruk-Hai', 'Uruk-Hai'), ('Medio Orcos', 'Medio Orcos'), ('Trolls', 'Trolls'), ('Olog-Hai', 'Olog-Hai'), ('Medio Trolls', 'Medio Trolls')], max_length=100),
        ),
    ]
