# Generated by Django 4.1.7 on 2023-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0004_alter_razayprofesion_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car1', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car2', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car3', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car4', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car5', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car6', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('car7', models.CharField(choices=[('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=20)),
                ('var11', models.IntegerField()),
                ('var12', models.IntegerField()),
                ('var13', models.IntegerField()),
                ('var14', models.IntegerField()),
                ('var15', models.IntegerField()),
                ('var16', models.IntegerField()),
                ('var17', models.IntegerField()),
                ('var21', models.IntegerField()),
                ('var22', models.IntegerField()),
                ('var23', models.IntegerField()),
                ('var24', models.IntegerField()),
                ('var25', models.IntegerField()),
                ('var26', models.IntegerField()),
                ('var27', models.IntegerField()),
            ],
        ),
    ]
