# Generated by Django 4.1.7 on 2023-04-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0005_tiradas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiradas',
            name='car1',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car2',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car3',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car4',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car5',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car6',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='car7',
        ),
    ]
