# Generated by Django 4.1.7 on 2023-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0006_remove_tiradas_car1_remove_tiradas_car2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiradas',
            old_name='var11',
            new_name='var1',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var12',
            new_name='var2',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var13',
            new_name='var3',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var14',
            new_name='var4',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var15',
            new_name='var5',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var16',
            new_name='var6',
        ),
        migrations.RenameField(
            model_name='tiradas',
            old_name='var17',
            new_name='var7',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var21',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var22',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var23',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var24',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var25',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var26',
        ),
        migrations.RemoveField(
            model_name='tiradas',
            name='var27',
        ),
    ]
