# Generated by Django 4.1.7 on 2023-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0007_rename_var11_tiradas_var1_rename_var12_tiradas_var2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caract1', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract2', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract3', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract4', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract5', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract6', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
                ('caract7', models.CharField(choices=[('---', '---'), ('FUE', 'FUE'), ('AGI', 'AGI'), ('CON', 'CON'), ('INT', 'INT'), ('I', 'I'), ('PRE', 'PRE'), ('APA', 'APA')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Tiradas',
        ),
    ]
