# Generated by Django 4.1.7 on 2023-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0009_alter_datosbasicos_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicos',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosbasicos',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
