# Generated by Django 4.0.5 on 2023-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0010_alter_datosbasicos_edad_alter_datosbasicos_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razayprofesion',
            name='dominio_magico',
            field=models.CharField(choices=[('Esencia', 'Esencia'), ('Canalizacion', 'Canalización')], max_length=100),
        ),
        migrations.AlterField(
            model_name='razayprofesion',
            name='profesion',
            field=models.CharField(choices=[('Guerrero', 'Guerrero'), ('Montaraz', 'Montaraz'), ('Explorador', 'Explorador'), ('Mago', 'Mago'), ('Animista', 'Animista'), ('Bardo', 'Bardo')], max_length=100),
        ),
    ]
