# Generated by Django 4.0.5 on 2023-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0011_alter_razayprofesion_dominio_magico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbasicos',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosbasicos',
            name='familia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
