# Generated by Django 4.0.5 on 2023-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0012_datosbasicos_experiencia_datosbasicos_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades_Secundarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hab_sec', models.CharField(max_length=20)),
                ('caracteristica', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RazasIdiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=20)),
                ('idiomas', models.CharField(max_length=255)),
            ],
        ),
    ]
