# Generated by Django 4.1.7 on 2023-05-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0015_razasidiomas_grados_alter_razasidiomas_idiomas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
