# Generated by Django 4.0.5 on 2023-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0016_delete_personaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortilegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.CharField(max_length=20)),
                ('dominio', models.IntegerField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
    ]
