# Generated by Django 4.0.5 on 2023-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0017_sortilegios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortilegios',
            name='dominio',
            field=models.CharField(max_length=20),
        ),
    ]
