# Generated by Django 4.1.7 on 2023-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionPJ', '0018_alter_sortilegios_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortilegios',
            name='dominio',
            field=models.CharField(max_length=30),
        ),
    ]
