# Generated by Django 4.0.5 on 2023-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardarPersonaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje_habsec',
            name='especial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
