# Generated by Django 4.1.7 on 2023-05-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardarPersonaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje_habsec',
            name='especial',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Personaje_pdh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdh', models.CharField(max_length=64)),
                ('Personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuardarPersonaje.personaje')),
            ],
        ),
    ]
