# Generated by Django 4.0.5 on 2022-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=20)),
                ('caracteristica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepj', models.CharField(max_length=20)),
                ('jugador', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('estatura', models.CharField(max_length=10)),
                ('peso', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('pelo', models.CharField(max_length=15)),
                ('ojos', models.CharField(max_length=15)),
                ('especialfisico', models.CharField(max_length=50)),
                ('personalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('motivacion', models.CharField(blank=True, max_length=20, null=True)),
                ('alineamiento', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('profesion', models.CharField(max_length=10)),
                ('nivel', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dominiomagico', models.CharField(max_length=20)),
                ('fuerza', models.IntegerField()),
                ('agilidad', models.IntegerField()),
                ('constitucion', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('intuicion', models.IntegerField()),
                ('presencia', models.IntegerField()),
                ('apariencia', models.IntegerField()),
                ('sinarmadura', models.IntegerField()),
                ('cuero', models.IntegerField()),
                ('cueroendurecido', models.IntegerField()),
                ('cotademallas', models.IntegerField()),
                ('coraza', models.IntegerField()),
                ('defilo', models.IntegerField()),
                ('contundente', models.IntegerField()),
                ('a2manos', models.IntegerField()),
                ('arrojadizas', models.IntegerField()),
                ('proyectiles', models.IntegerField()),
                ('armasdeasta', models.IntegerField()),
                ('escudo', models.IntegerField()),
                ('trepar', models.IntegerField()),
                ('montar', models.IntegerField()),
                ('nadar', models.IntegerField()),
                ('rastrear', models.IntegerField()),
                ('emboscar', models.IntegerField()),
                ('acecharyesconderse', models.IntegerField()),
                ('abrircerraduras', models.IntegerField()),
                ('desactivartrampas', models.IntegerField()),
                ('percepcion', models.IntegerField()),
                ('liderazgoeinfluencia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CreacionDatosBasicos',
                'verbose_name_plural': 'pjcreations',
            },
        ),
    ]
