# Generated by Django 4.0.5 on 2022-06-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habsecundaria',
            options={'verbose_name': 'HabSecundaria', 'verbose_name_plural': 'HabSecundarias'},
        ),
        migrations.AlterModelOptions(
            name='personaje',
            options={'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
    ]
