# Generated by Django 4.0.5 on 2022-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0002_alter_habsecundaria_options_alter_personaje_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=20)),
                ('opcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonajeDatosBasicosModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrepj', models.CharField(max_length=20)),
                ('jugador', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('estatura', models.CharField(max_length=10)),
                ('peso', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('pelo', models.CharField(max_length=15)),
                ('ojos', models.CharField(max_length=15)),
                ('especialfisico', models.CharField(max_length=50)),
                ('personalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('motivacion', models.CharField(blank=True, max_length=20, null=True)),
                ('alineamiento', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('profesion', models.CharField(max_length=10)),
                ('nivel', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dominiomagico', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
