# Generated by Django 4.0.5 on 2022-07-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0003_choicesmodel_personajedatosbasicosmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoicesModel',
        ),
        migrations.DeleteModel(
            name='HabSecundaria',
        ),
        migrations.DeleteModel(
            name='PersonajeDatosBasicosModel',
        ),
    ]
