# Generated by Django 4.0.5 on 2022-07-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PJCreation', '0004_delete_choicesmodel_delete_habsecundaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonajeDatosBasicosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepj', models.CharField(max_length=20)),
                ('jugador', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('estatura', models.FloatField()),
                ('peso', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('pelo', models.CharField(max_length=15)),
                ('ojos', models.CharField(max_length=15)),
                ('especialfisico', models.CharField(max_length=50)),
                ('personalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('motivacion', models.CharField(blank=True, max_length=20, null=True)),
                ('alineamiento', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('profesion', models.CharField(max_length=10)),
                ('nivel', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dominiomagico', models.CharField(max_length=20)),
            ],
        ),
    ]
