# Generated by Django 4.0.5 on 2022-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonajeCaracteristicasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue', models.IntegerField()),
                ('agi', models.IntegerField()),
                ('con', models.IntegerField()),
                ('int', models.IntegerField()),
                ('i', models.IntegerField()),
                ('PRE', models.IntegerField()),
                ('APA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonajeGradosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_armadura', models.IntegerField()),
                ('cuero', models.IntegerField()),
                ('cuero_endurecido', models.IntegerField()),
                ('cota_de_mallas', models.IntegerField()),
                ('coraza', models.IntegerField()),
                ('de_filo', models.IntegerField()),
                ('contundente', models.IntegerField()),
                ('a_2_manos', models.IntegerField()),
                ('arrojadizas', models.IntegerField()),
                ('proyectiles', models.IntegerField()),
                ('armas_de_asta', models.IntegerField()),
                ('escudo', models.IntegerField()),
                ('trepar', models.IntegerField()),
                ('montar', models.IntegerField()),
                ('nadar', models.IntegerField()),
                ('rastrear', models.IntegerField()),
                ('emboscar', models.IntegerField()),
                ('acechar_y_esconderse', models.IntegerField()),
                ('abrir_cerraduras', models.IntegerField()),
                ('desactivar_trampas', models.IntegerField()),
                ('percepcion', models.IntegerField()),
                ('liderazgo_e_influencia', models.IntegerField()),
            ],
        ),
    ]
