# Generated by Django 4.0.5 on 2022-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0006_personajecaracteristicasmodel_personajegradosmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personajecaracteristicasmodel',
            old_name='APA',
            new_name='apa',
        ),
        migrations.RenameField(
            model_name='personajecaracteristicasmodel',
            old_name='PRE',
            new_name='pre',
        ),
        migrations.AlterField(
            model_name='personajedatosbasicosmodel',
            name='raza',
            field=models.CharField(max_length=30),
        ),
    ]
