# Generated by Django 4.0.5 on 2022-07-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJCreation', '0007_rename_apa_personajecaracteristicasmodel_apa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajedatosbasicosmodel',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='personajedatosbasicosmodel',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personajedatosbasicosmodel',
            name='raza',
            field=models.CharField(max_length=20),
        ),
    ]
